<?xml version="1.0" encoding="utf-8"?><Database Name="driverlist" Class="driverlistDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\driverlist.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="driverlistConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.driver" Member="drivers">
    <Type Name="driver">
      <Column Name="driverID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="driverName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="driverGender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="driverStatus" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="driverAddress" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="driverContact" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="driverIC" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>