<?xml version="1.0" encoding="utf-8"?><Database Name="reviews" Class="reviewsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\reviews.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="reviewsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.reviews" Member="reviews">
    <Type Name="review">
      <Column Name="reviewsID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="customerID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="rating" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="comments" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>